// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wospdquyvrdrycjbsusm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indvc3BkcXV5dnJkcnljamJzdXNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxODQ4OTMsImV4cCI6MjA2MDc2MDg5M30.qxfm3pjRuQzWbt0ytj1YAZvNg2NUheMw37Wq9xhXJXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);